In [1]:
import pandas as pd
import numpy as np

# Step 1 ( Data Ingestion and Validation)

In [4]:
call_logs = pd.read_csv("C:/Users/gvrk1/Downloads/call_logs(assignment).csv")
agent_roster= pd.read_csv("C:/Users/gvrk1/Downloads/agent_roster(Assignment).csv")
disposition_summary = pd.read_csv("C:/Users/gvrk1/Downloads/disposition_summary(Assignment).csv")

In [6]:
### Call_logs data

In [8]:
print(call_logs.head())
print(call_logs.info())
print(call_logs.columns)

  call_id agent_id org_id installment_id     status  duration  \
0   C5333     A020     O2          L1826  completed      5.68
1   C3045     A018     O1          L1996  no_answer     14.27
2   C5803     A018     O1          L1849     failed     11.01
3   C2139     A007     O1          L1046  connected      9.02
4   C4814     A003     O1          L1887  completed      2.42

            created_ts   call_date
0  2025-04-28T15:40:00  28-04-2025
1  2025-04-28T02:41:00  28-04-2025
2  2025-04-28T19:42:00  28-04-2025
3  2025-04-28T09:52:00  28-04-2025
4  2025-04-28T12:58:00  28-04-2025
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   call_id         500 non-null    object
 1   agent_id        500 non-null    object
 2   org_id          500 non-null    object
 3   installment_id  500 non-null    object
 4   status          500 non-null    object
 5   duration        500 non-null    float64
 6   created_ts      500 non-null    object
 7   call_date       500 non-null    object
dtypes: float64(1), object(7)
memory usage: 31.4+ KB
None
Index(['call_id', 'agent_id', 'org_id', 'installment_id', 'status', 'duration',
       'created_ts', 'call_date'],
      dtype='object')

In [10]:
# cleaning the column names
call_logs.columns = call_logs.columns.str.strip()

In [12]:
#checking the data types
call_logs.dtypes

call_id            object
agent_id           object
org_id             object
installment_id     object
status             object
duration          float64
created_ts         object
call_date          object
dtype: object

In [16]:
#converting call_date column to datatime format
call_logs['call_date'] = pd.to_datetime(call_logs['call_date'], dayfirst = True )

In [18]:
call_logs.dtypes

call_id                   object
agent_id                  object
org_id                    object
installment_id            object
status                    object
duration                 float64
created_ts                object
call_date         datetime64[ns]
dtype: object

In [20]:
#null values
print(call_logs[['agent_id', 'org_id', 'call_date']].isnull().sum())

agent_id     0
org_id       0
call_date    0
dtype: int64

In [22]:
#duplicate values
print("Duplicate rows in call_logs:", call_logs.duplicated().sum())

Duplicate rows in call_logs: 0

### Agent_roster data

In [27]:
print(agent_roster.head())
print(agent_roster.info())
print(agent_roster.columns)

  agent_id users_first_name users_last_name users_office_location org_id
0     A001      AgentFirst1      AgentLast1             Bangalore     O1
1     A002      AgentFirst2      AgentLast2                 Delhi     O1
2     A003      AgentFirst3      AgentLast3                Mumbai     O1
3     A004      AgentFirst4      AgentLast4             Bangalore     O3
4     A005      AgentFirst5      AgentLast5             Bangalore     O3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   agent_id               20 non-null     object
 1   users_first_name       20 non-null     object
 2   users_last_name        20 non-null     object
 3   users_office_location  20 non-null     object
 4   org_id                 20 non-null     object
dtypes: object(5)
memory usage: 932.0+ bytes
None
Index(['agent_id', 'users_first_name', 'users_last_name',
       'users_office_location', 'org_id'],
      dtype='object')

In [29]:
#cleaning the column names
agent_roster.columns = agent_roster.columns.str.strip()

In [31]:
#checking the data types
agent_roster.dtypes

agent_id                 object
users_first_name         object
users_last_name          object
users_office_location    object
org_id                   object
dtype: object

In [33]:
#null values
print(agent_roster[['agent_id', 'org_id']].isnull().sum())

agent_id    0
org_id      0
dtype: int64

In [35]:
#duplicate values
print("Duplicate rows in agent_roster:", agent_roster.duplicated().sum())

Duplicate rows in agent_roster: 0

### Disposition_summary data

In [38]:
print(disposition_summary.head())
print(disposition_summary.info())
print(disposition_summary.columns)

  agent_id org_id   call_date login_time
0     A001     O1  28-04-2025      11:58
1     A002     O1  28-04-2025      10:05
2     A003     O1  28-04-2025      10:24
3     A004     O3  28-04-2025      08:13
4     A005     O3  28-04-2025        NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   agent_id    20 non-null     object
 1   org_id      20 non-null     object
 2   call_date   20 non-null     object
 3   login_time  17 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes
None
Index(['agent_id', 'org_id', 'call_date', 'login_time'], dtype='object')

In [40]:
#cleaning the column names
disposition_summary.columns = disposition_summary.columns.str.strip()

In [42]:
#Checking the data types
disposition_summary.dtypes

agent_id      object
org_id        object
call_date     object
login_time    object
dtype: object

In [44]:
#converting call_date column to datatime format
disposition_summary['call_date'] = pd.to_datetime(disposition_summary['call_date'], dayfirst = True)

In [46]:
disposition_summary.dtypes

agent_id              object
org_id                object
call_date     datetime64[ns]
login_time            object
dtype: object

In [48]:
#null values
print(disposition_summary[['agent_id', 'org_id', 'call_date']].isnull().sum())

agent_id     0
org_id       0
call_date    0
dtype: int64

In [50]:
#Duplicate values
print("Duplicate rows in disposition_summary:", disposition_summary.duplicated().sum())

Duplicate rows in disposition_summary: 0

# Step 2 (Join Logic)

In [53]:
#Ensuring the consistent data types for joining
call_logs['agent_id'] = call_logs['agent_id'].astype(str)
agent_roster['agent_id'] = agent_roster['agent_id'].astype(str)
disposition_summary['agent_id'] = disposition_summary['agent_id'].astype(str)

call_logs['org_id'] = call_logs['org_id'].astype(str)
agent_roster['org_id'] = agent_roster['org_id'].astype(str)
disposition_summary['org_id'] = disposition_summary['org_id'].astype(str)

In [55]:
# merging - call_logs and agent_roster
df_merge = call_logs.merge(agent_roster, on = ['agent_id', 'org_id'], how = 'left')

In [57]:
# merging the result with disposition_summary
df_merge = df_merge.merge(disposition_summary, on = ['agent_id', 'org_id', 'call_date'],how = 'left')

In [59]:
# add presence (1 if login_time exists, else 0)
df_merge['presence'] = df_merge['login_time'].notnull().astype(int)

In [61]:
df_merge['presence']

0      1
1      0
2      0
3      1
4      1
      ..
495    1
496    1
497    1
498    0
499    1
Name: presence, Length: 500, dtype: int32

In [63]:
# Merged data
print(df_merge.head())

  call_id agent_id org_id installment_id     status  duration  \
0   C5333     A020     O2          L1826  completed      5.68
1   C3045     A018     O1          L1996  no_answer     14.27
2   C5803     A018     O1          L1849     failed     11.01
3   C2139     A007     O1          L1046  connected      9.02
4   C4814     A003     O1          L1887  completed      2.42

            created_ts  call_date users_first_name users_last_name  \
0  2025-04-28T15:40:00 2025-04-28     AgentFirst20     AgentLast20
1  2025-04-28T02:41:00 2025-04-28     AgentFirst18     AgentLast18
2  2025-04-28T19:42:00 2025-04-28     AgentFirst18     AgentLast18
3  2025-04-28T09:52:00 2025-04-28      AgentFirst7      AgentLast7
4  2025-04-28T12:58:00 2025-04-28      AgentFirst3      AgentLast3

  users_office_location login_time  presence
0                 Delhi      09:50         1
1             Bangalore        NaN         0
2             Bangalore        NaN         0
3             Bangalore      08:36         1
4                Mumbai      10:24         1

In [65]:
# shape of the merged data
print(df_merge.shape)

(500, 13)

# Step 3 (Feature Engineering)

In [68]:
# Group by agent, org, date, first name, last name, presence
agent_day_groups = df_merge.groupby([
    'agent_id', 
    'org_id',
    'call_date',
    'users_first_name', 
    'users_last_name',
    'presence'])

In [70]:
# Calculating total calls
total_calls = agent_day_groups['call_id'].count().reset_index(name = 'total_calls')

In [72]:
total_calls

,agent_id,org_id,call_date,users_first_name,users_last_name,presence,total_calls
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,1,20
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,1,23
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,1,21
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,1,27
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,0,29
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,1,16
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,1,24
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,1,29
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,1,26
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,1,38
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,1,22
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,0,20
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,1,22
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,1,30
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,1,28
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,1,22
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,1,20
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,0,35
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,1,27
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,1,21

In [74]:
# Calculating unique loans contacted
unique_loans = agent_day_groups['installment_id'].nunique().reset_index(name = 'unique_loans_contacted')

In [76]:
unique_loans

,agent_id,org_id,call_date,users_first_name,users_last_name,presence,unique_loans_contacted
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,1,20
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,1,23
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,1,21
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,1,27
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,0,28
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,1,16
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,1,23
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,1,29
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,1,25
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,1,38
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,1,22
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,0,20
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,1,22
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,1,30
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,1,27
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,1,22
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,1,19
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,0,34
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,1,27
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,1,21

In [78]:
df_merge['is_completed'] = df_merge['status'].str.lower() == 'completed'

In [80]:
# Calculating number of completed calls
completed_calls = agent_day_groups['is_completed'].sum().reset_index(name = 'completed_calls')

In [82]:
completed_calls

,agent_id,org_id,call_date,users_first_name,users_last_name,presence,completed_calls
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,1,2
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,1,3
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,1,8
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,1,4
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,0,4
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,1,2
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,1,5
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,1,8
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,1,7
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,1,7
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,1,5
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,0,5
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,1,2
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,1,10
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,1,4
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,1,6
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,1,2
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,0,6
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,1,6
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,1,7

In [84]:
# Calculating average call duration
average_duration = agent_day_groups['duration'].mean().reset_index(name = 'avg_call_duration')

In [86]:
average_duration

,agent_id,org_id,call_date,users_first_name,users_last_name,presence,avg_call_duration
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,1,6.843000
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,1,7.827826
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,1,7.169524
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,1,8.056667
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,0,7.059310
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,1,8.837500
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,1,7.040417
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,1,6.603103
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,1,7.387308
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,1,8.078947
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,1,9.066818
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,0,7.103500
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,1,6.876364
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,1,7.701000
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,1,8.508214
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,1,8.701818
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,1,6.672500
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,0,7.489143
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,1,6.917778
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,1,6.562857

#### merging all the results together

In [89]:
summary = total_calls.merge(unique_loans, on = ['agent_id', 'org_id', 'call_date', 'users_first_name', 'users_last_name', 'presence'])

In [91]:
summary = summary.merge(completed_calls, on = ['agent_id', 'org_id', 'call_date', 'users_first_name', 'users_last_name', 'presence'])

In [93]:
summary = summary.merge(average_duration, on = ['agent_id', 'org_id', 'call_date', 'users_first_name', 'users_last_name', 'presence'])

In [95]:
summary

,agent_id,org_id,call_date,users_first_name,users_last_name,presence,total_calls,unique_loans_contacted,completed_calls,avg_call_duration
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,1,20,20,2,6.843000
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,1,23,23,3,7.827826
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,1,21,21,8,7.169524
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,1,27,27,4,8.056667
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,0,29,28,4,7.059310
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,1,16,16,2,8.837500
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,1,24,23,5,7.040417
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,1,29,29,8,6.603103
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,1,26,25,7,7.387308
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,1,38,38,7,8.078947
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,1,22,22,5,9.066818
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,0,20,20,5,7.103500
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,1,22,22,2,6.876364
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,1,30,30,10,7.701000
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,1,28,27,4,8.508214
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,1,22,22,6,8.701818
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,1,20,19,2,6.672500
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,0,35,34,6,7.489143
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,1,27,27,6,6.917778
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,1,21,21,7,6.562857

In [97]:
# Calculating the connect rate
summary['connect_rate'] = (summary['completed_calls'] / summary['total_calls']*100).round(2)

In [99]:
summary['connect_rate']

0     10.00
1     13.04
2     38.10
3     14.81
4     13.79
5     12.50
6     20.83
7     27.59
8     26.92
9     18.42
10    22.73
11    25.00
12     9.09
13    33.33
14    14.29
15    27.27
16    10.00
17    17.14
18    22.22
19    33.33
Name: connect_rate, dtype: float64

In [103]:
summary.head()
summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   agent_id                20 non-null     object
 1   org_id                  20 non-null     object
 2   call_date               20 non-null     datetime64[ns]
 3   users_first_name        20 non-null     object
 4   users_last_name         20 non-null     object
 5   presence                20 non-null     int32
 6   total_calls             20 non-null     int64
 7   unique_loans_contacted  20 non-null     int64
 8   completed_calls         20 non-null     int64
 9   avg_call_duration       20 non-null     float64
 10  connect_rate            20 non-null     float64
dtypes: datetime64[ns](1), float64(2), int32(1), int64(3), object(4)
memory usage: 1.8+ KB

# Step 4 (Output)

In [106]:
summary.to_csv("agent_performance_summary.csv", index=False)

In [108]:
Agent_performance_summary = pd.read_csv("agent_performance_summary.csv")

In [110]:
Agent_performance_summary

,agent_id,org_id,call_date,users_first_name,users_last_name,presence,total_calls,unique_loans_contacted,completed_calls,avg_call_duration,connect_rate
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,1,20,20,2,6.843000,10.00
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,1,23,23,3,7.827826,13.04
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,1,21,21,8,7.169524,38.10
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,1,27,27,4,8.056667,14.81
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,0,29,28,4,7.059310,13.79
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,1,16,16,2,8.837500,12.50
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,1,24,23,5,7.040417,20.83
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,1,29,29,8,6.603103,27.59
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,1,26,25,7,7.387308,26.92
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,1,38,38,7,8.078947,18.42
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,1,22,22,5,9.066818,22.73
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,0,20,20,5,7.103500,25.00
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,1,22,22,2,6.876364,9.09
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,1,30,30,10,7.701000,33.33
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,1,28,27,4,8.508214,14.29
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,1,22,22,6,8.701818,27.27
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,1,20,19,2,6.672500,10.00
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,0,35,34,6,7.489143,17.14
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,1,27,27,6,6.917778,22.22
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,1,21,21,7,6.562857,33.33

In [112]:
report_date = summary['call_date'].iloc[0].strftime('%Y-%m-%d')

In [114]:
# Top performer (highest connect rate)
top_agent = summary.loc[summary['connect_rate'].idxmax()]

In [116]:
top_name = f"{top_agent['users_first_name']} {top_agent['users_last_name']}"

In [118]:
top_rate = top_agent['connect_rate']

In [120]:
report_date

'2025-04-28'

In [128]:
top_agent

agent_id                                 A003
org_id                                     O1
call_date                 2025-04-28 00:00:00
users_first_name                  AgentFirst3
users_last_name                    AgentLast3
presence                                    1
total_calls                                21
unique_loans_contacted                     21
completed_calls                             8
avg_call_duration                    7.169524
connect_rate                             38.1
Name: 2, dtype: object

In [130]:
top_name

'AgentFirst3 AgentLast3'

In [132]:
top_rate

38.1

In [134]:
# Total active agents 
active_agents = summary[summary['presence'] == 1].shape[0]

In [136]:
# Average call duration across all the agents
average_duration = round(summary['avg_call_duration'].mean(),2)

In [138]:
average_duration

7.53

In [140]:
# Slack style
print(f"""
Agent Summary for {report_date}
Top performer: {top_name} ({top_rate}% connect rate)
Total Active Agents: {active_agents}
Average Duration: {average_duration} min
""")

Agent Summary for 2025-04-28
Top performer: AgentFirst3 AgentLast3 (38.1% connect rate)
Total Active Agents: 17
Average Duration: 7.53 min